#### Analysis of the significance of the dFC edges

Does coherence is fully explained by local power? This can be adressed via
the nodes-link inter-realtion coefficient (NLI):

$NIL_{ij} = <H[Z(POW_i)]H[Z(POW_j)]H[Z(COH_{ij})]> +
<\tilde{H}[Z(POW_i)]\tilde{H}[Z(POW_j)]\tilde{H}[Z(COH_{ij})]>$

where,

$H[x] = x$, if $x >= 0$ and $\tilde{H}[x] = -x$, if $x <= 0$

In [75]:
# Path to the toolbox
import sys

sys.path.insert(1, "/home/vinicius/storage1/projects/GrayData-Analysis")

import os

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mne.viz import plot_connectivity_circle
from tqdm import tqdm

import GDa.graphics.plot as plot
from config import sessions

In [76]:
SMALL_SIZE, MEDIUM_SIZE, BIGGER_SIZE = plot.set_plot_config()

In [77]:
SMALL_SIZE, MEDIUM_SIZE, BIGGER_SIZE = plot.set_plot_config()
# Create directory to save figures
if not os.path.exists("../figures/significance_analysis"):
    os.makedirs("../figures/significance_analysis")

In [78]:
_ROOT = os.path.expanduser("~/funcog/gda/Results/lucy/significance_analysis")

In [79]:
a = pd.read_csv(os.path.join(_ROOT, "nedges_coh_141014.csv"))

In [80]:
del a["Unnamed: 0"]

In [81]:
b = a.groupby(["roi", "freqs", "p"]).sum().reset_index()

In [82]:
b

             roi  freqs   p  n_edges
0         AIP-DP    3.0  ks        2
1         AIP-DP    3.0   t        2
2         AIP-DP   11.0  ks        2
3         AIP-DP   11.0   t        2
4         AIP-DP   19.0  ks        2
...          ...    ...  ..      ...
5875  a9/46D-V6A   59.0   t        1
5876  a9/46D-V6A   67.0  ks        1
5877  a9/46D-V6A   67.0   t        1
5878  a9/46D-V6A   75.0  ks        1
5879  a9/46D-V6A   75.0   t        1

[5880 rows x 4 columns]

In [98]:
df = []
for session in sessions:
    file_name = os.path.join(_ROOT, f"nedges_coh_{session}.csv")
    if os.path.exists(file_name):
        # out = pd.read_csv(file_name)
        # del out["Unnamed: 0"]
        # df += [out.groupby(["roi", "freqs", "p"]).sum().reset_index()]
        df += [pd.read_csv(file_name)]
        del df[-1]["Unnamed: 0"]

In [105]:
df = pd.concat(df).groupby(["roi", "freqs", "p"]).sum().reset_index()

In [109]:
df.loc[df["roi"].isin(["AIP-AIP"])]

        roi  freqs   p  n_edges
0   AIP-AIP    3.0  ks       23
1   AIP-AIP    3.0   t       23
2   AIP-AIP   11.0  ks       23
3   AIP-AIP   11.0   t       23
4   AIP-AIP   19.0  ks       23
5   AIP-AIP   19.0   t       23
6   AIP-AIP   27.0  ks       23
7   AIP-AIP   27.0   t       23
8   AIP-AIP   35.0  ks       23
9   AIP-AIP   35.0   t       23
10  AIP-AIP   43.0  ks       23
11  AIP-AIP   43.0   t       23
12  AIP-AIP   51.0  ks       21
13  AIP-AIP   51.0   t       22
14  AIP-AIP   59.0  ks       21
15  AIP-AIP   59.0   t       21
16  AIP-AIP   67.0  ks       21
17  AIP-AIP   67.0   t       22
18  AIP-AIP   75.0  ks       20
19  AIP-AIP   75.0   t       19

In [108]:
df

              roi  freqs   p  n_edges
0         AIP-AIP    3.0  ks       23
1         AIP-AIP    3.0   t       23
2         AIP-AIP   11.0  ks       23
3         AIP-AIP   11.0   t       23
4         AIP-AIP   19.0  ks       23
...           ...    ...  ..      ...
29215  a9/46V-VIP   59.0   t        2
29216  a9/46V-VIP   67.0  ks        0
29217  a9/46V-VIP   67.0   t        0
29218  a9/46V-VIP   75.0  ks        2
29219  a9/46V-VIP   75.0   t        1

[29220 rows x 4 columns]